import { ExerciseLibItem, StrengthTemplate, BodyPart, Equipment } from "./strength-types";

// ====== Label Maps ======

export const BODY_PART_LABELS: Record<BodyPart, string> = {
  chest: "胸部",
  back: "背部",
  legs: "腿部",
  shoulders: "肩部",
  arms: "手臂",
  core: "核心",
  lower: "下肢",
  upper_push: "上肢推",
  upper_pull: "上肢拉",
  full_body: "全身/功能性",
};

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: "杠铃",
  dumbbell: "哑铃",
  cable: "绳索",
  bodyweight: "自重",
  machine: "器械",
  kettlebell: "壶铃",
  med_ball: "药球",
  band: "弹力带",
  bosu: "波速球",
  bench: "长凳",
  other: "其他",
};

// ====== Exercise Library (92 exercises) ======

export const EXERCISE_LIBRARY: ExerciseLibItem[] = [
  // ---- Barbell ----
  {
    id: "barbell-back-squat",
    name: "杠铃后蹲",
    body_part: "legs",
    equipment: "barbell",
    description: "将杠铃置于斜方肌上，双脚与肩同宽，屈膝屈髋下蹲至大腿与地面平行，伸膝伸髋还原。核心收紧，背部保持中立。",
    cue_points: [
      "杠铃置于斜方肌上部，非颈椎",
      "吸气下蹲，保持胸椎伸展",
      "膝关节与脚尖方向一致",
      "重心在足中，勿前倾脚跟离地",
      "底部短暂停顿，爆发性站起"
    ],
    progression: "1.5 倍深蹲（底部停顿后起至半程再下蹲）/ 暂停后蹲（底部停 2 秒消除牵张反射）",
    regression: "高脚杯深蹲（哑铃置于胸前）—— 更容易保持躯干直立",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-back-squat-front.gif",
  },
  {
    id: "deadlift",
    name: "传统硬拉",
    body_part: "back",
    equipment: "barbell",
    description: "双脚与髋同宽，杠铃贴近小腿，屈髋后推、保持背部平直，握杠后伸髋伸膝拉起杠铃至站立位。",
    cue_points: [
      "杠铃全程贴近身体",
      "目视前方，勿低头看杠铃——低头导致圆背",
      "手臂仅作挂钩，勿主动屈肘/前臂发力",
      "启动时腋窝在杠铃正上方",
      "保持脊柱中立，勿弓背",
      "臀部先行发力，勿过早抬臀",
      "锁定位髋膝完全伸展，肩胛收紧"
    ],
    progression: "赤字硬拉（站在杠铃片上，增加运动范围）",
    regression: "架上硬拉（杠铃置于膝高处开始）—— 减少下背部压力",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-deadlift-front.gif",
  },
  {
    id: "bench-press",
    name: "杠铃卧推",
    body_part: "chest",
    equipment: "barbell",
    description: "仰卧于平凳上，握距略宽于肩，下放杠铃至胸部，推起至肘关节锁定。",
    cue_points: [
      "肩胛骨收紧并下沉",
      "双脚踏实地面，建立稳定支点",
      "杠铃触胸点：乳头连线位置",
      "肘关节与身体呈 45° 角，勿外展 90°",
      "推起时想象「掰弯杠铃」激活胸肌"
    ],
    progression: "暂停卧推（底部停顿 2 秒）—— 消除牵张反射",
    regression: "哑铃卧推 —— 更大的活动范围，减少肩关节压力",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-bench-press-front.gif",
  },
  {
    id: "overhead-press",
    name: "杠铃推举",
    body_part: "shoulders",
    equipment: "barbell",
    description: "站立位，杠铃置于锁骨前方，向上推举至头顶上方锁定，控制下放。核心收紧防后仰。",
    cue_points: [
      "握距略宽于肩",
      "腹部和臀肌收紧，防腰椎过度伸展",
      "杠铃轨迹为直线，经过面部时头微后仰",
      "顶部锁定，杠铃在耳后",
      "下放时控制离心，勿砸回锁骨"
    ],
    progression: "站姿单臂哑铃推举（增加核心抗侧屈需求）/ 暂停推举（底部锁定位停顿2秒）",
    regression: "坐姿哑铃推举 —— 消除下肢借力，更安全",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-overhead-press-front.gif",
  },
  {
    id: "bent-over-row",
    name: "杠铃俯身划船",
    body_part: "back",
    equipment: "barbell",
    description: "俯身至躯干与地面约 45°，握杠铃，沿大腿方向拉起至下腹部，顶峰收缩后控制下放。",
    cue_points: [
      "髋关节铰链，保持脊柱中立",
      "肘关节贴近身体",
      "肩胛骨先启动再带动手臂",
      "拉向肚脐位置",
      "下放时完全伸展背阔肌"
    ],
    progression: "潘德雷划船（每次从地面启动，消除牵张反射）",
    regression: "胸部支撑哑铃划船（俯卧斜板上）—— 减少下背负担",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-bent-over-row-front.gif",
  },
  {
    id: "romanian-deadlift",
    name: "罗马尼亚硬拉",
    body_part: "legs",
    equipment: "barbell",
    description: "站立握杠铃，微屈膝，髋部后推使杠铃沿腿前侧下降至小腿中部，伸髋还原。强调腘绳肌拉伸。",
    cue_points: [
      "膝关节微屈但角度不变",
      "臀部尽量后推",
      "杠铃始终贴腿",
      "感受腘绳肌拉伸，勿弓背",
      "伸髋发力回到站立位，臀部收紧"
    ],
    progression: "单腿罗马尼亚硬拉 —— 增加平衡和单侧力量要求",
    regression: "哑铃罗马尼亚硬拉 —— 对握力要求更低",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-romanian-deadlift-front.gif",
  },
  {
    id: "front-squat",
    name: "杠铃前蹲",
    body_part: "legs",
    equipment: "barbell",
    description: "杠铃置于锁骨前方，双手交叉或前架位支撑，保持躯干直立下蹲至大腿平行地面。",
    cue_points: [
      "肘关节抬高，保持杠铃稳定",
      "躯干较后蹲更直立",
      "下蹲深度应达大腿平行或更低",
      "核心全程紧绷防前倾",
      "起立时想象「肘关节引领」，防止躯干前倾——躯干角度保持与下蹲时一致"
    ],
    progression: "暂停前蹲（底部停 2 秒）",
    regression: "高脚杯深蹲 —— 姿势要求相同但负荷更轻",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-front-squat-front.gif",
  },

  // ---- Dumbbell ----
  {
    id: "dumbbell-lunges",
    name: "哑铃弓步走",
    body_part: "legs",
    equipment: "dumbbell",
    description: "双手各持哑铃，交替向前跨步至前后膝关节均约 90°，后膝接近地面但不触碰，前腿发力推回。",
    cue_points: [
      "上身保持直立，不过度前倾",
      "前膝与脚尖方向一致，勿内扣（膝关节在矢状面稳定）",
      "后膝微触地面或距地 2-3cm",
      "核心收紧维持平衡",
      "步幅适中，过大增加髋屈肌压力"
    ],
    progression: "反向弓步 + 膝驱动（加入爆发元素）",
    regression: "自重弓步 —— 先掌握动作模式",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-lunges-front.gif",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "哑铃推举",
    body_part: "shoulders",
    equipment: "dumbbell",
    description: "坐姿（有靠背），哑铃置于肩外侧，向上推至头顶，控制下放。",
    cue_points: [
      "腰背紧贴靠背",
      "哑铃轨迹略呈弧线但保持稳定",
      "不完全锁定肘关节以保持张力",
      "下放至耳侧位置即可",
      "避免耸肩，沉肩发力"
    ],
    progression: "单臂交替推举 —— 增加核心抗旋需求",
    regression: "阿诺德推举（旋转式推举）—— 更循序渐进",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-shoulder-press-front.gif",
  },
  {
    id: "goblet-squat",
    name: "高脚杯深蹲",
    body_part: "legs",
    equipment: "dumbbell",
    description: "双手托哑铃一端于胸前，肘关节在膝关节内侧，下蹲至大腿平行地面。适合初学者建立动作模式。",
    cue_points: [
      "哑铃始终贴近胸部",
      "肘关节触碰膝关节内侧",
      "躯干保持直立",
      "下蹲时吸气，起立时呼气",
      "脚跟不能离地"
    ],
    progression: "双哑铃前架位深蹲",
    regression: "自重箱式深蹲（坐到凳子上再起）",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-goblet-squat-front.gif",
  },

  // ---- Cable ----
  {
    id: "cable-row",
    name: "坐姿绳索划船",
    body_part: "back",
    equipment: "cable",
    description: "坐姿，双脚踩踏板，握 V 柄，挺胸收腹，将手柄拉向腹部，肩胛骨充分收缩。",
    cue_points: [
      "起始时背阔肌有拉伸感",
      "先启动肩胛后缩再屈肘",
      "手柄拉至腹部，肩胛充分收紧",
      "回放时保持控制，不耸肩前送",
      "躯干稳定不前后摇摆"
    ],
    progression: "单臂绳索划船 —— 更大的活动范围",
    regression: "弹力带坐姿划船 —— 可变阻力更友好",
    image_url: "https://musclewiki.com/media/uploads/male-cable-seated-row-front.gif",
  },
  {
    id: "tricep-pushdown",
    name: "绳索三头下压",
    body_part: "arms",
    equipment: "cable",
    description: "站姿，高位滑轮，握绳索或直杆，上臂固定于体侧，伸肘下压至手臂伸直。",
    cue_points: [
      "上臂贴近身体固定",
      "运动只发生在肘关节",
      "底部充分收缩三头肌",
      "回放时控制，不完全屈肘",
      "身体不前倾借力"
    ],
    progression: "仰卧杠铃臂屈伸 —— 更大负重",
    regression: "弹力带三头下压 —— 更轻阻力",
    image_url: "https://musclewiki.com/media/uploads/male-cable-tricep-pushdown-front.gif",
  },
  {
    id: "face-pull",
    name: "绳索面拉",
    body_part: "shoulders",
    equipment: "cable",
    description: "高位滑轮，握绳索两端，拉向面部，双手分开至耳侧，肩外旋，激活后束和肩袖。",
    cue_points: [
      "将绳索拉向额头或眼睛高度",
      "双手向外旋转，拇指指向后方",
      "肩胛骨充分后缩",
      "控制离心阶段",
      "重量宜轻，强调动作质量"
    ],
    progression: "单臂绳索面拉",
    regression: "弹力带面拉 —— 阻力曲线更平滑",
    image_url: "https://musclewiki.com/media/uploads/male-cable-face-pull-front.gif",
  },

  // ---- Bodyweight ----
  {
    id: "pull-up",
    name: "引体向上",
    body_part: "back",
    equipment: "bodyweight",
    description: "正握单杠，握距略宽于肩，从完全悬垂位拉起至下巴过杠，控制下放。核心收紧，身体不摆动。",
    cue_points: [
      "起始位肩胛完全上提，背阔肌拉伸",
      "启动时先沉肩，肩胛下抑",
      "胸部拉向杠，非下巴",
      "全程身体不摆动借力",
      "顶部短暂停留挤压背阔肌"
    ],
    progression: "负重引体向上（腰带挂杠铃片）/ 离心引体（跳起后控制下放 5 秒）",
    regression: "弹力带辅助引体向上 / 高位下拉",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-pullup-front.gif",
  },
  {
    id: "push-up",
    name: "俯卧撑",
    body_part: "chest",
    equipment: "bodyweight",
    description: "手略宽于肩，身体成一直线，屈肘下降至胸部近地面，推起至肘关节锁定。",
    cue_points: [
      "身体从头到脚一条直线",
      "核心和臀部收紧",
      "肘关节与身体呈 45°",
      "下降至胸部距地 5cm",
      "推起时呼气"
    ],
    progression: "负重俯卧撑 / 吊环俯卧撑",
    regression: "跪姿俯卧撑 / 上斜俯卧撑（手高位）",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-pushup-front.gif",
  },

  // ---- Machine ----
  {
    id: "lat-pulldown",
    name: "高位下拉",
    body_part: "back",
    equipment: "machine",
    description: "坐姿，大腿固定垫，宽握横杆，挺胸后仰微角，下拉至锁骨位置，控制上放至起始位。",
    cue_points: [
      "握距约为肩宽 1.5 倍",
      "下拉时先沉肩再屈肘",
      "横杆拉至锁骨/上胸部",
      "躯干不前后摇摆",
      "回放时充分伸展背阔肌"
    ],
    progression: "颈后高位下拉（需良好肩关节活动度）",
    regression: "弹力带下拉 —— 更适合初学者",
    image_url: "https://musclewiki.com/media/uploads/male-machine-lat-pulldown-front.gif",
  },
  {
    id: "leg-press",
    name: "腿举",
    body_part: "legs",
    equipment: "machine",
    description: "坐于腿举机，双脚与肩同宽置于踏板，解锁安全杆，屈膝至 90° 后伸膝还原。背部紧贴靠垫。",
    cue_points: [
      "全脚掌贴于踏板",
      "膝关节与脚尖方向一致",
      "下降至膝角 90° 即可，勿过深",
      "推起时不完全锁定膝关节",
      "腰部始终紧贴靠垫"
    ],
    progression: "单腿腿举 —— 纠正双侧不平衡",
    regression: "自重箱式深蹲",
    image_url: "https://musclewiki.com/media/uploads/male-machine-leg-press-front.gif",
  },
  {
    id: "cable-chest-fly",
    name: "绳索飞鸟",
    body_part: "chest",
    equipment: "cable",
    description: "站姿中立位，双手各握高位滑轮手柄，肘微屈固定角度，向胸前合拢手臂至双手相遇，控制张开。",
    cue_points: [
      "肘关节保持微屈且角度不变",
      "动作弧线如「抱大树」",
      "顶峰收缩胸肌 1 秒",
      "回放时感受胸肌拉伸",
      "身体不前后摆动借力"
    ],
    progression: "低位绳索飞鸟 —— 侧重上胸",
    regression: "哑铃飞鸟（平凳）",
    image_url: "https://musclewiki.com/media/uploads/male-cable-chest-fly-front.gif",
  },

  // ---- Bodyweight / Plyometric / Core (football-specific) ----
  {
    id: "nordic-hamstring-curl",
    name: "北欧腘绳肌弯举",
    body_part: "legs",
    equipment: "bodyweight",
    description: "跪姿，脚踝固定（搭档压住或器械固定），身体笔直，缓慢前倾至极限后用手缓冲推回。全程髋关节保持伸展，腘绳肌离心控制。",
    cue_points: [
      "髋关节始终保持伸展，身体从头到膝一条直线",
      "用腘绳肌控制下降速度，尽量慢放",
      "下降到无法控制时用手缓冲",
      "回推时尽量减少手臂辅助",
      "初期可从半程开始，逐步增加下降幅度"
    ],
    progression: "全程无手辅助（需极高腘绳肌离心力量）",
    regression: "半程下落（45°即回推）/ 弹力带辅助",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-nordic-hamstring-curl-front.gif",
  },
  {
    id: "box-jump",
    name: "跳箱",
    body_part: "legs",
    equipment: "bodyweight",
    description: "面对跳箱站立，屈膝摆臂爆发性跳上箱面，双脚同时落箱、膝关节缓冲吸收冲击。下箱时走下（勿跳下，保护跟腱）。",
    cue_points: [
      "摆臂充分，利用手臂动量辅助起跳",
      "双脚同时起跳同时落地",
      "落箱时膝关节微屈缓冲，重心稳定",
      "跳上非跳下——走下箱保护跟腱",
      "选择合适高度，保证落箱姿态完美为前提"
    ],
    progression: "负重跳箱（手持轻哑铃）/ 深蹲跳箱（从坐姿起跳）",
    regression: "台阶跳（矮箱）/ 反向跳箱（地面跳至最低箱面）",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-box-jump-front.gif",
  },
  {
    id: "pallof-press",
    name: "抗旋推",
    body_part: "core",
    equipment: "cable",
    description: "侧对绳索站立，双手握手柄于胸前，向正前方推出至肘伸直，保持 2 秒后收回。全程核心抗旋，躯干不随绳索旋转。",
    cue_points: [
      "双脚与肩同宽，微屈膝稳定下盘",
      "核心全程紧绷，对抗绳索拉力方向",
      "推出和收回速度一致，控制节奏",
      "躯干保持中立位，不倾斜不旋转",
      "两侧均等训练"
    ],
    progression: "单跪姿抗旋推（减少下盘支撑，增加核心挑战）",
    regression: "弹力带抗旋推（阻力更小）/ 减少推出距离",
    image_url: "https://musclewiki.com/media/uploads/male-cable-pallof-press-front.gif",
  },
  {
    id: "single-leg-rdl",
    name: "单腿罗马尼亚硬拉",
    body_part: "legs",
    equipment: "dumbbell",
    description: "单腿站立，对侧手持哑铃，支撑腿微屈膝，髋部后推使躯干前倾、自由腿向后伸展，保持髋部水平。哑铃沿支撑腿下降至小腿中部，伸髋还原。",
    cue_points: [
      "髋部保持水平，勿向自由腿侧倾斜",
      "支撑腿微屈膝但角度不变",
      "自由腿与躯干成一条直线向后延伸",
      "哑铃始终贴近支撑腿",
      "目视前下方地面，保持脊柱中立",
      "初期可扶墙辅助平衡"
    ],
    progression: "单腿 RDL + 膝驱动（还原时自由腿向前顶膝）",
    regression: "手扶墙/TRX 辅助单腿 RDL / 双侧罗马尼亚硬拉",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-single-leg-deadlift-front.gif",
  },

  // ============================================================
  // LOWER BODY（下肢）— 20 exercises
  // ============================================================

  {
    id: "bulgarian-split-squat",
    name: "保加利亚分腿蹲",
    body_part: "lower",
    equipment: "dumbbell",
    description: "后脚置于凳上，前腿屈膝下蹲至大腿平行地面，前腿发力推起还原。核心收紧保持躯干直立。",
    cue_points: [
      "后脚脚背置于凳面，前腿间距适中",
      "前腿膝关节与脚尖方向一致",
      "躯干略前倾但背部保持平直",
      "底部前腿大腿与地面平行",
      "前脚全掌发力推起，勿用后腿借力",
    ],
    progression: "负重保加利亚分腿蹲（双手持哑铃）/ 跳跃保加利亚分腿蹲",
    regression: "自重分腿蹲 —— 双脚着地，减少平衡需求",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-bulgarian-split-squat-front.gif",
  },
  {
    id: "split-squat",
    name: "分腿蹲",
    body_part: "lower",
    equipment: "bodyweight",
    description: "前后分腿站立，后膝下降接近地面，前腿发力推起。保持躯干直立，核心收紧。",
    cue_points: [
      "前后脚间距约一步半，重心居中",
      "后膝轻轻触地或离地 2-3cm",
      "前腿膝关节勿超过脚尖过多",
      "核心收紧，骨盆中立位",
      "前脚全掌发力，推起时呼气",
    ],
    progression: "负重分腿蹲（双手持哑铃）",
    regression: "扶墙分腿蹲 —— 辅助平衡",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-split-squat-front.gif",
  },
  {
    id: "cossack-squat",
    name: "哥萨克深蹲",
    body_part: "lower",
    equipment: "bodyweight",
    description: "宽站距，重心侧移至一侧腿，屈膝下蹲至大腿平行地面，对侧腿伸直脚尖朝上。左右交替。",
    cue_points: [
      "站距约肩宽 1.5-2 倍",
      "重心移向弯曲腿，伸直腿脚尖勾起朝上",
      "弯曲腿全脚掌着地，膝关节与脚尖方向一致",
      "躯干保持直立，核心收紧",
      "左右交替，动作流畅连贯",
    ],
    progression: "负重哥萨克深蹲（持壶铃或哑铃于胸前）",
    regression: "手扶支撑物辅助平衡",
    image_url: "",
  },
  {
    id: "sumo-squat",
    name: "宽距深蹲",
    body_part: "lower",
    equipment: "dumbbell",
    description: "宽站距脚尖外展，双手持哑铃于体前，屈膝屈髋下蹲至大腿平行地面，伸膝伸髋还原。",
    cue_points: [
      "站距宽于肩，脚尖外展约 30°",
      "膝关节与脚尖方向一致，勿内扣",
      "躯干保持直立，哑铃垂直下垂",
      "底部内收肌有拉伸感",
      "伸髋发力推起，臀部收紧",
    ],
    progression: "杠铃宽距深蹲 —— 更大负重",
    regression: "自重宽距深蹲",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-sumo-squat-front.gif",
  },
  {
    id: "barbell-hip-thrust",
    name: "杠铃臀冲",
    body_part: "lower",
    equipment: "barbell",
    description: "上背部靠凳，杠铃横跨髋部，屈膝脚踏实地面，伸髋将杠铃推至最高点，臀部充分收缩。",
    cue_points: [
      "肩胛骨下缘靠凳边缘",
      "杠铃置于髋关节褶皱处，可用垫保护",
      "下巴微收，目视前方",
      "顶峰收缩臀肌 1-2 秒",
      "下放时控制，勿塌腰",
    ],
    progression: "单腿臀冲 —— 增加单侧力量要求",
    regression: "自重臀桥 —— 掌握髋伸动作模式",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-hip-thrust-front.gif",
  },
  {
    id: "weighted-glute-bridge",
    name: "负重臀桥",
    body_part: "lower",
    equipment: "dumbbell",
    description: "仰卧屈膝，哑铃置于髋部，伸髋抬臀至肩-髋-膝成直线，顶峰收缩臀肌后控制下放。",
    cue_points: [
      "双脚与髋同宽，平踏地面",
      "发力时臀部收紧，勿过度伸展腰椎",
      "顶峰保持 1-2 秒",
      "下放时臀部轻触地面即可",
      "整个动作过程核心收紧",
    ],
    progression: "单腿负重臀桥 —— 增加稳定性要求",
    regression: "自重臀桥",
    image_url: "https://musclewiki.com/media/uploads/male-barbell-hip-thrust-front.gif",
  },
  {
    id: "single-leg-glute-bridge",
    name: "单侧臀桥",
    body_part: "lower",
    equipment: "bodyweight",
    description: "仰卧，一侧腿屈膝支撑，对侧腿伸直抬起，伸髋抬臀至肩-髋-膝成直线，控制下放。",
    cue_points: [
      "支撑腿全脚掌踏地，膝与脚尖方向一致",
      "抬起腿保持伸直，与躯干在同一平面",
      "髋部保持水平，勿向一侧倾斜",
      "顶峰收缩臀肌 1-2 秒",
      "核心收紧，勿塌腰代偿",
    ],
    progression: "负重单侧臀桥（哑铃置于支撑侧髋部）",
    regression: "双侧臀桥 —— 先建立基础力量",
    image_url: "",
  },
  {
    id: "kneeling-hip-extension",
    name: "跪姿伸髋",
    body_part: "lower",
    equipment: "bodyweight",
    description: "四足跪姿，一侧腿屈膝 90° 向后上方伸髋，至大腿与躯干平齐，臀肌收缩后控制下放。",
    cue_points: [
      "手在肩正下方，膝在髋正下方",
      "保持核心收紧，脊柱中立位",
      "伸髋时脚尖朝向地面，膝关节角度不变",
      "运动只发生在髋关节，不塌腰",
      "顶峰收缩臀肌 1 秒",
    ],
    progression: "弹力带跪姿伸髋 —— 增加阻力",
    regression: "减小运动幅度",
    image_url: "",
  },
  {
    id: "rapid-hip-thrust",
    name: "快速挺髋",
    body_part: "lower",
    equipment: "bodyweight",
    description: "仰卧屈膝，快速爆发性伸髋抬臀，强调动作速率。每组完成 10-15 次快速重复。",
    cue_points: [
      "发力迅猛，伸髋速度最大化",
      "顶峰短暂锁定",
      "下落控制但不过慢",
      "核心全程收紧，防腰椎过度伸展",
      "每组保持一致的爆发节奏",
    ],
    progression: "弹力带快速挺髋 —— 增加可变阻力",
    regression: "慢速臀桥 —— 先建立动作控制",
    image_url: "",
  },
  {
    id: "kettlebell-single-leg-rdl",
    name: "壶铃单腿RDL",
    body_part: "lower",
    equipment: "kettlebell",
    description: "单腿站立，对侧手持壶铃，髋部后推躯干前倾，自由腿后伸，壶铃沿支撑腿下降至小腿中部。",
    cue_points: [
      "髋部保持水平，不向自由腿侧翻转",
      "支撑腿微屈膝但角度不变",
      "自由腿与躯干成直线向后延伸",
      "壶铃贴近支撑腿，轨迹垂直",
      "感受腘绳肌拉伸后伸髋还原",
    ],
    progression: "壶铃单腿 RDL + 膝驱动",
    regression: "手扶墙单腿 RDL —— 减少平衡难度",
    image_url: "",
  },
  {
    id: "seated-calf-raise",
    name: "坐姿负重足跖屈",
    body_part: "lower",
    equipment: "dumbbell",
    description: "坐姿，哑铃置于膝上大腿远端，前掌踩踏板或台阶边缘，提踵至最高点后控制下落。",
    cue_points: [
      "前脚掌着力，脚跟悬空",
      "上提至最大跖屈角度",
      "顶峰收缩小腿肌群 1 秒",
      "下放时充分拉伸小腿后侧",
      "节奏均匀，不借助惯性",
    ],
    progression: "单腿坐姿提踵 —— 增加单侧负荷",
    regression: "自重坐姿提踵",
    image_url: "",
  },
  {
    id: "standing-calf-raise",
    name: "站姿提踵",
    body_part: "lower",
    equipment: "bodyweight",
    description: "站立位，前掌踩台阶边缘，脚跟悬空，提踵至最高点后控制下落至低于水平面。",
    cue_points: [
      "站姿稳定，可扶墙辅助",
      "匀速上提至最大跖屈",
      "顶峰收缩 1 秒",
      "充分下放拉伸跟腱和小腿",
      "膝关节保持微屈不锁死",
    ],
    progression: "单腿站姿提踵 / 负重站姿提踵（手持哑铃）",
    regression: "平地自重提踵 —— 减少运动范围",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-standing-calf-raise-front.gif",
  },
  {
    id: "rapid-calf-raise",
    name: "快速提踵",
    body_part: "lower",
    equipment: "bodyweight",
    description: "站立位前掌着地，快速连续提踵，强调踝关节刚性（stiffness）和跖屈速率，每组 20-30 次。",
    cue_points: [
      "脚跟快速弹起，触地时间最短化",
      "踝关节保持刚性，不过度屈膝借力",
      "保持节奏稳定，不减速",
      "注意力在小腿快速收缩",
      "可作为跳跃训练的辅助练习",
    ],
    progression: "单腿快速提踵",
    regression: "慢速提踵 —— 先建立基础力量",
    image_url: "",
  },
  {
    id: "barbell-squat-jump",
    name: "杠铃深蹲跳",
    body_part: "lower",
    equipment: "barbell",
    description: "杠铃置于斜方肌上（轻负荷 20-30% 1RM），下蹲后爆发性起跳，落地缓冲衔接下一次。",
    cue_points: [
      "负重轻，动作速度优先",
      "下蹲至 1/4 或半蹲角度起跳",
      "三关节（髋-膝-踝）同时伸展",
      "落地屈膝缓冲，声音轻",
      "落地后立即衔接下一次下蹲",
    ],
    progression: "杠铃深蹲跳 + 垂直跳（去除杠铃）超级组",
    regression: "自重深蹲跳 —— 先掌握起跳和落地技术",
    image_url: "",
  },
  {
    id: "squat-to-sprint",
    name: "深蹲衔接冲刺跑",
    body_part: "lower",
    equipment: "bodyweight",
    description: "自重深蹲到底部后，爆发性站起并立即转为 5-10m 加速冲刺。强调力量到速度的转换。",
    cue_points: [
      "深蹲到底部大腿至少平行地面",
      "从底部爆发性站起，手臂积极摆动",
      "站起后无缝衔接冲刺，不犹豫",
      "冲刺阶段手臂和膝关节高频率驱动",
      "核心紧绷，全程躯干稳定",
    ],
    progression: "负重深蹲衔接冲刺 —— 增加力量要求",
    regression: "深蹲衔接慢跑 —— 降低速度要求",
    image_url: "",
  },
  {
    id: "kettlebell-goblet-split-squat",
    name: "壶铃高脚杯分腿蹲",
    body_part: "lower",
    equipment: "kettlebell",
    description: "双手托壶铃于胸前（高脚杯握法），前后分腿站立，后膝下降接近地面，前腿发力推起还原。核心收紧保持躯干直立。",
    cue_points: [
      "壶铃始终贴近胸部，肘关节自然下垂",
      "前腿膝关节与脚尖方向一致，勿内扣",
      "后膝轻触地面或距地 2-3cm",
      "躯干保持直立，核心收紧维持平衡",
      "前脚全掌发力推起，控制离心下降",
    ],
    progression: "双壶铃分腿蹲 —— 增加总负荷",
    regression: "自重分腿蹲 —— 先掌握动作模式",
    image_url: "",
  },
  {
    id: "hamstring-glute-bridge",
    name: "大腿后侧臀桥",
    body_part: "lower",
    equipment: "bodyweight",
    description: "仰卧，脚跟置于凳面或地面（脚跟位置比常规臀桥更远），屈膝约 90°，伸髋抬臀至肩-髋-膝成直线，重点感受腘绳肌和臀肌收缩。",
    cue_points: [
      "脚跟支撑，脚尖可微微翘起减少小腿参与",
      "发力时先收紧臀肌再抬髋",
      "顶峰时肩-髋-膝成直线，臀部充分收缩",
      "下放控制，臀部轻触地面即可",
      "注意力集中在腘绳肌和臀肌，非腰椎",
    ],
    progression: "单腿大腿后侧臀桥 / 负重臀桥（哑铃置于髋部）",
    regression: "常规臀桥（双脚靠近臀部）—— 减少腘绳肌参与",
    image_url: "",
  },
  {
    id: "lateral-lunge",
    name: "侧弓步",
    body_part: "lower",
    equipment: "bodyweight",
    description: "站立位，向一侧跨出大步，屈膝下蹲至大腿平行地面，对侧腿保持伸直，支撑腿发力推回起始位。左右交替。锻炼内收肌和下肢侧向稳定性。",
    cue_points: [
      "跨步脚全脚掌着地，脚尖略外展",
      "弯曲腿膝关节与脚尖方向一致",
      "对侧腿伸直，脚底贴地",
      "躯干保持直立或微前倾，核心收紧",
      "推回时弯曲腿发力，控制节奏",
    ],
    progression: "负重侧弓步（持壶铃或哑铃于胸前）",
    regression: "手扶支撑物侧弓步 —— 辅助平衡",
    image_url: "",
  },
  {
    id: "lunge-squat",
    name: "弓箭步蹲",
    body_part: "lower",
    equipment: "bodyweight",
    description: "站立位，一脚向前跨步，前后膝关节均屈至约 90°，后膝接近地面，前腿发力推回起始位。原地完成，非行进间。核心收紧保持躯干直立。",
    cue_points: [
      "前腿膝关节与脚尖方向一致，勿超过脚尖过多",
      "后膝轻触地面或距地 2-3cm",
      "躯干保持直立，不前倾后仰",
      "前脚全掌发力推回，蹬地有力",
      "节奏可控，下放 2 秒推起 1 秒",
    ],
    progression: "负重弓箭步蹲（双手持哑铃）/ 后脚抬高弓箭步蹲",
    regression: "扶墙弓箭步蹲 —— 辅助平衡",
    image_url: "",
  },
  {
    id: "walking-lunge",
    name: "连续弓箭步",
    body_part: "lower",
    equipment: "bodyweight",
    description: "站立位，向前跨步完成弓箭步后，后腿蹬地向前迈进衔接下一次弓箭步，交替行进。强调动作连贯性和动态稳定性。",
    cue_points: [
      "每步下蹲至前后膝关节均约 90°",
      "后膝轻触地面后立即蹬地推进",
      "躯干全程保持直立，不左右摇摆",
      "核心收紧维持骨盆稳定",
      "步幅适中，过大影响连贯性",
    ],
    progression: "负重连续弓箭步（双手持哑铃）/ 过顶持重弓箭步走",
    regression: "原地弓箭步蹲 —— 先建立单次动作模式",
    image_url: "",
  },

  // ============================================================
  // UPPER BODY PUSH（上肢推）— 7 exercises
  // ============================================================

  {
    id: "dumbbell-bench-press",
    name: "哑铃卧推",
    body_part: "upper_push",
    equipment: "dumbbell",
    description: "仰卧平凳，双手持哑铃于胸两侧，推起至手臂伸直，控制下放。肩胛收紧，双脚踏实地面。",
    cue_points: [
      "肩胛骨收紧下沉，胸部挺起",
      "哑铃下放至胸侧，肘与身体呈 45°",
      "推起时哑铃弧线向内收拢",
      "顶峰勿完全锁定肘关节，保持胸肌张力",
      "下放时感受胸肌拉伸，节奏可控",
    ],
    progression: "单臂交替哑铃卧推 —— 增加核心抗旋需求",
    regression: "轻哑铃卧推 / 地板卧推 —— 减少运动范围",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-bench-press-front.gif",
  },
  {
    id: "single-leg-db-bench-press",
    name: "单腿哑铃卧推",
    body_part: "upper_push",
    equipment: "dumbbell",
    description: "仰卧平凳，一侧脚抬起离地，仅单腿支撑，在此姿势下完成哑铃卧推。核心收紧防身体旋转。",
    cue_points: [
      "抬起的腿保持伸直，脚离地约 10cm",
      "支撑脚踏实地面，维持身体稳定",
      "核心全程紧绷，防骨盆旋转",
      "哑铃推举动作与常规卧推一致",
      "两侧交替进行以均衡发展",
    ],
    progression: "双腿抬起卧推 —— 核心挑战更大",
    regression: "常规哑铃卧推 —— 去掉稳定性的额外挑战",
    image_url: "",
  },
  {
    id: "single-arm-kettlebell-press",
    name: "单臂壶铃上举",
    body_part: "upper_push",
    equipment: "kettlebell",
    description: "站姿单手持壶铃于肩外侧（架铃位），向上推至头顶上方，核心抗侧屈维持躯干中立。",
    cue_points: [
      "壶铃置于前臂外侧，手腕中立",
      "核心全程收紧，防躯干侧倾",
      "壶铃轨迹直线上行",
      "顶部锁定，肱二头肌靠近耳朵",
      "下放控制，刻意对抗离心力",
    ],
    progression: "单臂壶铃借力推举 —— 加入微屈膝蹬伸",
    regression: "坐姿单臂壶铃推举 —— 减少核心稳定要求",
    image_url: "https://musclewiki.com/media/uploads/male-kettlebell-overhead-press-front.gif",
  },
  {
    id: "med-ball-overhead-slam",
    name: "药球过顶下砸",
    body_part: "upper_push",
    equipment: "med_ball",
    description: "站姿持药球高举过头，全力向下砸向地面，接反弹后连贯重复。强调爆发性屈髋和上肢发力。",
    cue_points: [
      "药球高举过头，充分伸展躯干",
      "全力向下砸，三关节同时屈曲发力",
      "球触地瞬间不要减速",
      "接反弹后直接举过顶，动作连贯",
      "核心收紧，保护腰椎",
    ],
    progression: "跳跃药球下砸 —— 增加起跳高度和砸球力量",
    regression: "轻药球下砸 —— 降低负荷和冲击",
    image_url: "",
  },
  {
    id: "lying-med-ball-chest-push",
    name: "躺姿橡胶球平推",
    body_part: "upper_push",
    equipment: "med_ball",
    description: "仰卧，双手持药球于胸前，爆发性将球向天花板推出，接住后控制下放至胸前。",
    cue_points: [
      "肩胛骨收紧，背部贴紧地面",
      "爆发性推球，手臂完全伸展",
      "球推到最高点时双手离开球面",
      "接球时手臂顺势缓冲",
      "核心收紧，身体不弹起",
    ],
    progression: "单臂躺姿推球 —— 增加单侧爆发力要求",
    regression: "双手慢速推球 —— 减少爆发成分",
    image_url: "",
  },
  {
    id: "dynamic-pushup",
    name: "动态俯卧撑",
    body_part: "upper_push",
    equipment: "bodyweight",
    description: "俯卧撑姿势，推起时双手离地并拍手/触摸肩膀/前后交替，落地缓冲后连贯完成下一次。",
    cue_points: [
      "身体从头到脚一条直线，核心收紧",
      "推起爆发力足够双手离地",
      "落地屈肘缓冲，声音轻",
      "落地后立即衔接下一次",
      "根据能力选择拍手/摸肩/前后变式",
    ],
    progression: "击掌俯卧撑 / 双拍手俯卧撑",
    regression: "手高位的动态俯卧撑（手置于凳面）",
    image_url: "",
  },
  {
    id: "wide-pushup",
    name: "宽距俯卧撑",
    body_part: "upper_push",
    equipment: "bodyweight",
    description: "双手撑地，握距约为肩宽 1.5-2 倍，身体从头到脚一条直线，屈肘下降至胸部近地面，推起至肘关节锁定。宽握距增加胸肌外侧和三角肌前束参与。",
    cue_points: [
      "双手间距显著宽于肩，手指朝前或略外展",
      "身体从头到脚一条直线，核心和臀部收紧",
      "下降时肘关节向外打开但勿过度",
      "胸部降至距地 5cm，感受胸肌拉伸",
      "推起时胸部发力，勿耸肩",
    ],
    progression: "宽距负重俯卧撑 / 宽距吊环俯卧撑",
    regression: "膝着地宽距俯卧撑 —— 减少负荷",
    image_url: "",
  },

  // ============================================================
  // UPPER BODY PULL（上肢拉）— 4 exercises
  // ============================================================

  {
    id: "dumbbell-row",
    name: "哑铃划船",
    body_part: "upper_pull",
    equipment: "dumbbell",
    description: "单手扶凳，同侧膝置凳面，对侧手持哑铃，背部发力将哑铃拉向髋侧，顶峰收缩后控制下放。",
    cue_points: [
      "背部保持平直，躯干与地面接近平行",
      "先启动肩胛后缩，再屈肘拉动哑铃",
      "哑铃拉向髋部外侧而非胸前",
      "顶峰时肩胛充分收缩",
      "下放时感受背阔肌拉伸，不完全放松",
    ],
    progression: "单臂哑铃划船 + 躯干微旋转（增加活动范围）",
    regression: "胸部支撑哑铃划船（俯卧斜板）—— 减少下背负担",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-row-front.gif",
  },
  {
    id: "inverted-row",
    name: "反向引体向上",
    body_part: "upper_pull",
    equipment: "bodyweight",
    description: "双手握杠铃杆（置于深蹲架安全杆），身体斜卧，脚跟着地，将胸部拉向杠铃杆，控制下放。",
    cue_points: [
      "身体从头到脚一条直线，臀肌收紧",
      "握距略宽于肩",
      "将胸部拉向横杆，非下巴",
      "顶峰时肩胛骨充分后缩",
      "下放时充分伸展背阔肌",
    ],
    progression: "抬高脚部反向引体（脚置于凳上）/ 加重背心反向引体",
    regression: "屈膝反向引体（脚平踏地面）—— 减少杠杆臂长度",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-inverted-row-front.gif",
  },
  {
    id: "band-face-pull",
    name: "弹力带面拉",
    body_part: "upper_pull",
    equipment: "band",
    description: "将弹力带固定于面部高度，双手握弹力带两端，拉向面部，双手分开至耳侧，肩外旋。",
    cue_points: [
      "弹力带固定点与眼同高",
      "拉向额头/眼睛位置",
      "双手向外旋转，拇指指向后方",
      "肩胛骨充分后缩",
      "控制离心，缓慢还原",
    ],
    progression: "单臂弹力带面拉",
    regression: "选择更轻阻力的弹力带",
    image_url: "",
  },
  {
    id: "trx-row",
    name: "TRX划船",
    body_part: "upper_pull",
    equipment: "other",
    description: "双手握 TRX 手柄，身体后仰斜卧，脚跟支撑，将胸部拉向手柄，顶峰收缩背部后控制下放。",
    cue_points: [
      "身体倾斜角度决定难度（越水平越难）",
      "从头到脚一条直线，臀肌收紧",
      "手掌相对或正握均可",
      "拉向胸下部，肩胛后缩先行",
      "下放时控制节奏，充分伸展",
    ],
    progression: "单臂 TRX 划船 —— 增加抗旋需求",
    regression: "站位更直立 —— 减少自身体重负荷比例",
    image_url: "",
  },

  // ============================================================
  // CORE（核心）— 15 exercises
  // ============================================================

  {
    id: "plank",
    name: "平板支撑",
    body_part: "core",
    equipment: "bodyweight",
    description: "俯卧，前臂与脚尖支撑，身体从头到脚一条直线，核心收紧保持静态。从 30 秒开始逐步增加时长。",
    cue_points: [
      "肘在肩正下方，前臂平贴地面",
      "核心收紧，腹肌-臀肌-股四头肌同时发力",
      "骨盆微后倾，避免腰椎下沉",
      "呼吸均匀，不憋气",
      "头颈与脊柱成直线，目视地面",
    ],
    progression: "单腿平板支撑 / 抬手平板支撑 / 负重平板",
    regression: "膝着地平板支撑 —— 减少杠杆臂长度",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-plank-front.gif",
  },
  {
    id: "dead-bug",
    name: "死虫式",
    body_part: "core",
    equipment: "bodyweight",
    description: "仰卧，四肢朝天，对侧手臂和腿同时向地面伸展，保持核心收紧、腰部贴地，交替进行。",
    cue_points: [
      "腰部始终贴紧地面，不留空隙",
      "运动缓慢且有控制，非快速摆动",
      "伸展时吸气，还原时呼气",
      "未伸展的一侧保持稳定不晃动",
      "注意力在腹横肌，感受核心紧绷",
    ],
    progression: "持轻哑铃/弹力带死虫式 —— 增加四肢负荷",
    regression: "只移动腿/只移动手臂 —— 减少协调要求",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-dead-bug-front.gif",
  },
  {
    id: "bird-dog",
    name: "鸟狗式",
    body_part: "core",
    equipment: "bodyweight",
    description: "四足跪姿，对侧手臂和腿同时伸展至与躯干平齐，保持核心稳定、骨盆不旋转，交替进行。",
    cue_points: [
      "手在肩正下方，膝在髋正下方",
      "伸展时保持骨盆水平，不向支撑侧倾斜",
      "移动缓慢，如同在水下运动",
      "伸展至极限时保持 1-2 秒",
      "核心全程收紧，脊柱中立",
    ],
    progression: "鸟狗式 + 膝肘触碰（收回时肘碰膝）",
    regression: "只伸腿或只伸手 —— 先建立单侧模式",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-bird-dog-front.gif",
  },
  {
    id: "copenhagen-plank",
    name: "哥本哈根支撑",
    body_part: "core",
    equipment: "bodyweight",
    description: "侧卧，上侧腿置于凳上，下侧前臂支撑，抬髋使身体成直线，内收肌和核心同时发力。",
    cue_points: [
      "上侧腿膝关节搁在凳面上",
      "身体从头到脚成一条直线",
      "髋部不塌陷也不过度上抬",
      "核心和内侧大腿同时发力",
      "两侧等时训练",
    ],
    progression: "哥本哈根支撑 + 上侧腿外展 / 增加保持时间",
    regression: "膝位哥本哈根支撑（膝而非脚踝置凳）—— 减小杠杆臂",
    image_url: "",
  },
  {
    id: "russian-twist",
    name: "俄罗斯转体",
    body_part: "core",
    equipment: "bodyweight",
    description: "坐姿，躯干后仰约 45°，双脚离地或着地，双手合十左右旋转躯干，核心紧绷控制节奏。",
    cue_points: [
      "躯干后仰角度不变，不前倾",
      "旋转主要来自胸椎而非腰椎",
      "核心全程紧绷，双腿稳定",
      "节奏可控，不依赖惯性",
      "目视双手，头部随身体转动",
    ],
    progression: "负重俄罗斯转体（持药球或哑铃片）",
    regression: "双脚着地俄罗斯转体 —— 减少核心稳定需求",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-russian-twist-front.gif",
  },
  {
    id: "bosu-russian-twist",
    name: "波速球俄罗斯转体",
    body_part: "core",
    equipment: "bosu",
    description: "坐在波速球平面侧上，完成俄罗斯转体动作。不稳定的支撑面增加核心激活程度。",
    cue_points: [
      "坐在波速球中心，保持平衡",
      "躯干后仰角度固定",
      "旋转时控制幅度，勿失去平衡",
      "核心全程紧绷对抗不稳定",
      "动作可控，不依赖惯性",
    ],
    progression: "波速球负重俄罗斯转体",
    regression: "地面俄罗斯转体 —— 减少不稳定因素",
    image_url: "",
  },
  {
    id: "v-up",
    name: "两头起",
    body_part: "core",
    equipment: "bodyweight",
    description: "仰卧，手臂和双腿同时抬起，手触脚尖，形成 V 字形，控制下放至起始位。",
    cue_points: [
      "手臂和双腿同步启动和结束",
      "上半身离地时下巴微收，防颈部用力",
      "顶峰时手臂和腿均伸直",
      "下放时控制离心速度",
      "呼吸：抬起时呼气，下放时吸气",
    ],
    progression: "负重两头起（手持轻哑铃或脚踝沙袋）",
    regression: "单交替两头起（每次只抬一侧）—— 减少难度",
    image_url: "",
  },
  {
    id: "opposite-arm-leg-raise",
    name: "对侧起",
    body_part: "core",
    equipment: "bodyweight",
    description: "俯卧，手臂前伸，同时抬起对侧手臂和腿，保持核心收紧，交替进行。强化后链和核心稳定。",
    cue_points: [
      "俯卧，额头轻触地面",
      "缓慢抬起对侧手臂和腿，至极限",
      "顶峰保持 1-2 秒",
      "不抬起的肢体保持贴地",
      "感受背部、臀部和核心的协同收缩",
    ],
    progression: "超人式（同时抬起双臂双腿）",
    regression: "仅抬腿或仅抬手 —— 先建立单侧模式",
    image_url: "",
  },
  {
    id: "adductor-raise",
    name: "内收肌抬起",
    body_part: "core",
    equipment: "bodyweight",
    description: "侧卧，下方腿伸直，上方腿屈膝跨至前方，下方腿内侧发力抬起，控制下放。锻炼内收肌。",
    cue_points: [
      "下方腿保持伸直，脚尖朝前",
      "上方腿屈膝置于前方地面稳定身体",
      "下侧腿内侧发力抬起",
      "运动范围不大，感受内收肌",
      "两侧等量训练",
    ],
    progression: "弹力带内收肌抬起 —— 增加阻力",
    regression: "减小运动幅度",
    image_url: "",
  },
  {
    id: "plank-shoulder-tap",
    name: "平板摸肩",
    body_part: "core",
    equipment: "bodyweight",
    description: "俯卧撑支撑位，单手交替触摸对侧肩膀，核心和肩带保持稳定，骨盆不旋转或晃动。",
    cue_points: [
      "双手在肩正下方，身体从头到脚一条直线",
      "触摸时骨盆保持水平，不旋转",
      "核心和臀肌收紧固定身体",
      "动作缓慢且有控制",
      "两脚间距可略宽以增加稳定性",
    ],
    progression: "平板摸肩 + 抬对侧腿",
    regression: "膝着地平板摸肩 —— 减少杠杆臂长度",
    image_url: "",
  },
  {
    id: "saw-plank",
    name: "拉锯平板支撑",
    body_part: "core",
    equipment: "bodyweight",
    description: "前臂平板支撑位，身体前后微移（向前后锯动），在移动中保持核心稳定，身体仍成直线。",
    cue_points: [
      "前臂与脚尖支撑，身体成直线",
      "身体缓慢前后移动，幅度约 5-10cm",
      "核心全程紧绷，不塌腰",
      "移动中保持身体直线不变形",
      "呼吸均匀，不憋气",
    ],
    progression: "拉锯平板 + 使用滑盘或毛巾增加运动范围",
    regression: "静态平板支撑 —— 先建立基础耐力",
    image_url: "",
  },
  {
    id: "hollow-body-hold",
    name: "仰卧空体支撑",
    body_part: "core",
    equipment: "bodyweight",
    description: "仰卧，手臂和双腿微离地面，腰部贴地，核心收紧使身体呈弧形（香蕉状），保持静态时长。",
    cue_points: [
      "腰部全程贴地，不留空隙",
      "手臂和腿离地约 10-15cm",
      "下巴微收，颈部放松",
      "核心全程紧绷如同被重击准备",
      "呼吸均匀，不憋气，从 20 秒开始",
    ],
    progression: "空体摇摆（rocking）—— 小幅度前后摇摆",
    regression: "屈膝空体支撑（腿屈膝 90°）—— 减小杠杆臂",
    image_url: "",
  },
  {
    id: "side-plank",
    name: "侧支撑",
    body_part: "core",
    equipment: "bodyweight",
    description: "侧卧，单侧前臂支撑，身体成直线，髋部抬离地面，侧面核心和髋外展肌持续收缩。",
    cue_points: [
      "肘在肩正下方，前臂垂直身体",
      "髋部抬高，身体从头到脚一条直线",
      "非支撑侧手臂可放于髋部或指向天",
      "核心和臀肌收紧，勿塌髋",
      "两侧等时训练，从 20 秒开始",
    ],
    progression: "侧支撑 + 抬上侧腿 / 侧支撑 + 髋部下放再抬起",
    regression: "膝着地侧支撑 —— 减小杠杆臂",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-side-plank-front.gif",
  },
  {
    id: "banded-plank-variation",
    name: "弹力带平板变式",
    body_part: "core",
    equipment: "band",
    description: "平板支撑位，弹力带绕脚踝或手腕，在平板支撑基础上加入肢体外展或抗旋等变式。",
    cue_points: [
      "基础平板支撑姿势先建立稳定",
      "弹力带阻力适中，不影响动作质量",
      "肢体移动时核心锁定不动",
      "呼吸均匀，不因阻力而憋气",
      "可交替加入腿外展/手前伸等变式",
    ],
    progression: "弹力带平板 + 登山跑",
    regression: "无弹力带平板支撑",
    image_url: "",
  },
  {
    id: "sit-up",
    name: "仰卧起坐",
    body_part: "core",
    equipment: "bodyweight",
    description: "仰卧屈膝，双脚固定或自由，核心发力卷腹抬起上半身至坐立位，控制下放至起始位。",
    cue_points: [
      "下巴微收，颈部放松不代偿",
      "卷腹时腰椎逐节离地",
      "坐起时呼气，下放时吸气",
      "下放控制，不完全松弛",
      "双脚可勾住固定物或自由放置",
    ],
    progression: "负重仰卧起坐（胸前持哑铃片）/ 下斜仰卧起坐",
    regression: "卷腹（肩胛离地即可）—— 减少运动范围",
    image_url: "https://musclewiki.com/media/uploads/male-bodyweight-sit-up-front.gif",
  },

  // ============================================================
  // FULL BODY / FUNCTIONAL（全身/功能性）— 6 exercises
  // ============================================================

  {
    id: "trampoline-return-pass",
    name: "蹦床随机回传球",
    body_part: "full_body",
    equipment: "other",
    description: "面对蹦床站立，将球扔向蹦床使其随机反弹，快速反应接球后再次传出。训练手眼协调和反应速度。",
    cue_points: [
      "站姿中立位，随时准备移动",
      "盯住球，预判反弹轨迹",
      "脚步灵活移动至接球位置",
      "接球后快速回传，动作流畅",
      "可变换球的大小和反弹角度增加难度",
    ],
    progression: "单脚站立接球 / 接球后做动作再回传",
    regression: "缩短距离，减小反弹角度范围",
    image_url: "",
  },
  {
    id: "yoga-ball-push-circle",
    name: "瑜伽球前推画圆",
    body_part: "full_body",
    equipment: "other",
    description: "跪姿或站姿，双手置于瑜伽球上，向前推动瑜伽球并做顺时针/逆时针画圆，核心保持稳定。",
    cue_points: [
      "起始姿势核心收紧，脊柱中立",
      "球前推时身体倾斜角度由核心控制",
      "画圆时肩带稳定，手臂引导球",
      "运动范围在可控之内",
      "呼吸均匀，核心始终不放松",
    ],
    progression: "单臂瑜伽球画圆 / 在波速球上完成此动作",
    regression: "小幅度前推画圆 —— 减少活动范围",
    image_url: "",
  },
  {
    id: "standing-med-ball-catch",
    name: "站姿接药球",
    body_part: "full_body",
    equipment: "med_ball",
    description: "站姿中立位，搭档从不同方向抛出药球，快速反应接球后回传。训练上肢反应和手眼协调。",
    cue_points: [
      "膝关节微屈，重心在两脚之间",
      "双手随时准备接球",
      "接球瞬间顺势缓冲，不硬接",
      "目视球和搭档，预判来球方向",
      "可增加转身或移动后接球变式",
    ],
    progression: "单腿站立接药球 / 接球后立即完成一次下砸",
    regression: "缩短距离，减小球重和传球速度",
    image_url: "",
  },
  {
    id: "kettlebell-swing",
    name: "壶铃摇摆",
    body_part: "full_body",
    equipment: "kettlebell",
    description: "站姿宽距，双手持壶铃，屈髋后推壶铃从胯下后摆，伸髋爆发性将壶铃前摆至胸部高度。",
    cue_points: [
      "髋部铰链，非深蹲",
      "壶铃如同钟摆，手臂仅作连接",
      "伸髋爆发力驱动壶铃前摆",
      "顶点时臀肌和腹肌收紧",
      "壶铃自然下摆，不过早屈髋",
    ],
    progression: "单臂壶铃摇摆 / 双壶铃摇摆",
    regression: "缩短运动幅度 / 减轻壶铃重量",
    image_url: "https://musclewiki.com/media/uploads/male-kettlebell-swing-front.gif",
  },
  {
    id: "farmers-walk",
    name: "负重农夫行走",
    body_part: "full_body",
    equipment: "dumbbell",
    description: "双手各持重哑铃（或壶铃），自然站立，核心收紧，向前行走固定距离或时间。全身肌群协同稳定。",
    cue_points: [
      "肩胛下沉，肩带稳定",
      "核心全程紧绷，躯干直立",
      "步伐稳健，不蹒跚",
      "握力是限制因素，挑战握力极限",
      "行走时均匀呼吸，不憋气",
    ],
    progression: "单侧负重农夫行走 —— 增加核心抗侧屈需求",
    regression: "减轻负重 / 缩短行走距离",
    image_url: "https://musclewiki.com/media/uploads/male-dumbbell-farmers-walk-front.gif",
  },
  {
    id: "plate-rotation",
    name: "杠铃片交替转体",
    body_part: "full_body",
    equipment: "other",
    description: "站姿持杠铃片于胸前，核心收紧，左右旋转躯干将杠铃片交替传向身体两侧。强化旋转爆发力。",
    cue_points: [
      "双脚与肩同宽，膝关节微屈",
      "旋转来自胸椎而非腰椎",
      "核心全程紧绷，对抗惯性",
      "动作节奏可控，不依赖惯性回弹",
      "目视杠铃片，头部随身体转动",
    ],
    progression: "单臂杠铃片旋转 / 杠铃片旋转 + 弓箭步",
    regression: "无负重躯干旋转 —— 先建立动作控制",
    image_url: "",
  },

  // ============================================================
  // SAQ / AGILITY（速度敏捷）— 5 exercises
  // ============================================================

  {
    id: "fast-feet-in-place",
    name: "原地快速脚步",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "站立位微屈膝，前脚掌着地，最快速度原地交替踏步，手臂配合摆动。强调触地时间最短化和脚步频率最大化。",
    cue_points: [
      "前脚掌着地，脚跟不触地",
      "脚步频率尽可能快，如同「踩热炭」",
      "手臂短促快速摆动，配合下肢节奏",
      "膝关节微屈，核心收紧保持稳定",
      "可从 10 秒开始逐步延长至 30 秒",
    ],
    progression: "绳梯快速脚步 / 单腿原地快速脚步",
    regression: "慢速原地踏步 —— 先建立节奏感",
    image_url: "",
  },
  {
    id: "forward-back-alternate",
    name: "前后交替",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "站立位，双脚快速前后交替切换（剪刀步），前脚掌着地，手臂配合摆动。强调脚步切换速度和身体协调性。",
    cue_points: [
      "双脚前后快速交替，步幅短小",
      "前脚掌着地，重心在两脚之间",
      "手臂与下肢自然协调摆动",
      "核心收紧，躯干保持稳定",
      "保持节奏稳定，不因疲劳减速",
    ],
    progression: "前后交替 + 听口令冲刺 / 前后交替 + 绳梯",
    regression: "慢速前后交替 —— 先掌握协调模式",
    image_url: "",
  },
  {
    id: "lateral-leap",
    name: "侧向跨越跳",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "侧向站立，外侧腿蹬地发力向对侧跨越跳跃，落地屈膝缓冲后立即反向跳回。强调侧向爆发力和落地稳定性。",
    cue_points: [
      "起跳时外侧腿全力蹬伸，手臂向上摆动",
      "落地时屈膝屈髋缓冲，声音轻",
      "落地后立即衔接反向起跳，不犹豫",
      "核心收紧，躯干保持直立不侧倾",
      "跳跃距离适中，保证落地姿态稳定",
    ],
    progression: "单腿侧向跨越跳 / 栏架侧向跨越跳",
    regression: "侧向跨步（非跳跃）—— 先建立侧向移动模式",
    image_url: "",
  },
  {
    id: "step-crossover",
    name: "踏步交叉",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "侧向移动中，后腿交替从前方和后方交叉跨越前腿（葡萄步/卡里奥克步），强调髋关节灵活性和脚步协调。",
    cue_points: [
      "前腿侧跨一步，后腿交替前交叉和后交叉",
      "髋关节主动旋转配合交叉步",
      "手臂自然摆动辅助平衡",
      "核心收紧，躯干保持直立",
      "两侧方向均等训练",
    ],
    progression: "踏步交叉 + 冲刺 / 弹力带阻力踏步交叉",
    regression: "慢速踏步交叉 —— 先掌握协调模式",
    image_url: "",
  },
  {
    id: "outward-jump",
    name: "外跳跃",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "站立位，双脚同时向外侧跳开再跳回，如同开合跳的下半身版本。强调踝关节刚性和侧向爆发力。触地时间最短化。",
    cue_points: [
      "双脚同时向外跳开至比肩宽",
      "落地后立即跳回起始位，触地时间极短",
      "前脚掌着地，踝关节保持刚性",
      "膝关节微屈缓冲，核心收紧",
      "节奏快速连续，如同「弹跳球」",
    ],
    progression: "单腿外跳跃 / 外跳跃 + 向前冲刺",
    regression: "侧向踏步（非跳跃）—— 先建立侧向移动基础",
    image_url: "",
  },

  // ============================================================
  // PARTNER / FUNCTIONAL（搭档训练）— 8 exercises
  // ============================================================

  {
    id: "wheelbarrow-walk",
    name: "马步手推车",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "一人俯卧撑支撑位，搭档抬起其双腿（手推车姿势），前者用手向前「行走」固定距离。锻炼上肢推力、核心稳定和肩带耐力。",
    cue_points: [
      "支撑者身体从头到脚一条直线，核心收紧",
      "搭档握住支撑者小腿或脚踝，稳定跟随",
      "支撑者双手交替向前移动，步幅适中",
      "核心全程紧绷，不塌腰",
      "根据能力设定行走距离，两侧交替角色",
    ],
    progression: "马步手推车 + 下坡 / 单手马步手推车",
    regression: "膝着地手推车（减小力臂）—— 更易控制",
    image_url: "",
  },
  {
    id: "partner-carry",
    name: "抱着一个人",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "一人将搭档抱起（公主抱或消防员扛），向前行走固定距离。锻炼全身力量、核心稳定和功能性负重能力。",
    cue_points: [
      "抱起时屈膝下蹲用腿发力，非弯腰",
      "抱稳后核心收紧，躯干直立行走",
      "步伐稳健，不突然加速或转向",
      "被抱者放松配合，不挣扎晃动",
      "两侧交替角色，控制行走距离",
    ],
    progression: "消防员扛人走 / 双人负重接力",
    regression: "背负走（搭档背在背上）—— 更容易控制",
    image_url: "",
  },
  {
    id: "partner-back-support",
    name: "背人手撑",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "一人背对搭档站立，搭档双手撑在其背部施加阻力，前者向前行走对抗阻力。锻炼下肢推进力和核心抗前倾能力。",
    cue_points: [
      "前行者身体微前倾，核心收紧对抗阻力",
      "搭档均匀施力，不突然加大推力",
      "前行者步伐稳定，身体不过度前倾",
      "膝关节微屈，前脚掌发力推进",
      "两侧交替角色，控制行进距离",
    ],
    progression: "增加搭档施力强度 / 弹力带腰带阻力行走",
    regression: "无阻力行走 —— 先建立动作意识",
    image_url: "",
  },
  {
    id: "shoulder-resistance",
    name: "推肩阻力",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "一人站立，搭档双手置于其双肩施加向后的阻力，前者向前行走对抗肩部阻力。锻炼肩带稳定性和下肢推进力。",
    cue_points: [
      "前行者肩胛收紧，躯干保持直立",
      "搭档从肩部均匀向后施力",
      "前行者步伐短促有力，身体不后仰",
      "核心全程收紧，对抗阻力方向",
      "两侧交替角色，控制间距和速度",
    ],
    progression: "弹力带绕肩阻力行走 / 推肩阻力 + 侧向行走",
    regression: "双手扶墙对抗自重 —— 先体验阻力感",
    image_url: "",
  },
  {
    id: "leg-drag-walk",
    name: "拉着腿行走",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "一人俯卧于地面，搭档握住其脚踝向后拉，俯卧者用手臂向前「爬行」对抗拉力。锻炼上肢拉力、背部和核心力量。",
    cue_points: [
      "俯卧者身体保持直线，核心收紧",
      "手臂交替向前拉动身体，背部发力",
      "搭档控制拉力适中，不突然用力",
      "前进速度均匀，不因疲劳松懈核心",
      "两侧交替角色，控制距离",
    ],
    progression: "拉着腿行走 + 增加拉力 / 俯卧爬行（无阻力）",
    regression: "缩短爬行距离 —— 降低疲劳度",
    image_url: "",
  },
  {
    id: "core-battle",
    name: "核心对抗",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "两人面对面站立，双手互推、侧推或交替对抗，在动态对抗中保持核心稳定和身体平衡。训练核心抗旋和反应能力。",
    cue_points: [
      "膝关节微屈，重心降低稳定下盘",
      "核心全程紧绷，对抗搭档推力不后退",
      "推力来自核心和下肢而非仅手臂",
      "可变换对抗方向（正面/侧面/旋转）",
      "注意安全，控制力度，不突然发力",
    ],
    progression: "单腿站立核心对抗 / 闭眼核心对抗",
    regression: "静态互推（无移动）—— 先建立核心抗推意识",
    image_url: "",
  },
  {
    id: "standing-band-work",
    name: "站姿弹力带",
    body_part: "full_body",
    equipment: "band",
    description: "站立位，弹力带固定于身体前方或侧方，双手握弹力带完成推、拉、旋转等动作，在可变阻力下训练全身稳定性和力量。",
    cue_points: [
      "弹力带固定点高度根据训练目标调整",
      "核心全程收紧对抗弹力带拉力",
      "动作节奏可控，向心和离心均等重视",
      "可组合推/拉/旋转/侧屈等变式",
      "选择合适的弹力带阻力，动作质量为优先",
    ],
    progression: "单腿站姿弹力带 / 弹力带 + 不稳定平面（波速球）",
    regression: "坐姿弹力带 —— 减少下盘稳定需求",
    image_url: "",
  },
  {
    id: "partner-band-dynamic",
    name: "两个人弹力带动态",
    body_part: "full_body",
    equipment: "band",
    description: "两人各握弹力带一端，在动态移动中完成向上推、向前推、向外展等组合动作，弹力带产生可变阻力。训练全身协调和搭档配合。",
    cue_points: [
      "两人配合节奏，动作同步进行",
      "弹力带保持张力，不松弛",
      "核心全程收紧，控制身体姿态",
      "向上-向前-向外三个方向均等训练",
      "沟通明确，避免突然松手导致弹力带回弹",
    ],
    progression: "单腿站立搭档弹力带 / 搭档弹力带 + 移动行走",
    regression: "单人固定端弹力带 —— 先适应可变阻力",
    image_url: "",
  },

  // ============================================================
  // WARMUP / MOBILITY（热身激活）— 5 exercises
  // ============================================================

  {
    id: "crossover-step",
    name: "交叉步",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "侧向移动中，后腿交替从前方和后方交叉跨越前腿行进。激活髋关节旋转肌群，改善下肢协调性。常用于热身阶段的动态准备。",
    cue_points: [
      "侧向行进，前腿跨步后腿交替前交叉和后交叉",
      "髋关节主动旋转带动下肢",
      "手臂自然张开辅助平衡",
      "核心收紧，躯干保持直立",
      "两个方向（左右）均等训练",
    ],
    progression: "交叉步 + 冲刺 / 弹力带阻力交叉步",
    regression: "原地交叉步（非行进间）—— 先建立协调模式",
    image_url: "",
  },
  {
    id: "hip-adduction",
    name: "髋内收",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "站立位，一侧腿从外展位向内收方向摆动，跨过身体中线至对侧。动态激活内收肌群，提升髋关节活动范围。常用于热身阶段。",
    cue_points: [
      "支撑腿微屈膝保持稳定",
      "摆动腿直腿从外侧向内摆动",
      "摆动幅度在舒适范围内，不强行拉伸",
      "核心收紧，骨盆保持中立位",
      "两侧交替，动作流畅有节奏",
    ],
    progression: "弹力带髋内收 —— 增加阻力",
    regression: "扶墙髋内收 —— 减少平衡需求",
    image_url: "",
  },
  {
    id: "hip-abduction",
    name: "髋外展",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "站立位，一侧腿从内收位向外展方向摆动，远离身体中线。动态激活臀中肌和外展肌群，提升髋关节侧向稳定性。常用于热身阶段。",
    cue_points: [
      "支撑腿微屈膝保持稳定",
      "摆动腿直腿从内侧向外摆动",
      "摆动幅度在舒适范围内，不代偿倾斜躯干",
      "核心收紧，骨盆保持中立位不侧倾",
      "两侧交替，动作流畅有节奏",
    ],
    progression: "弹力带髋外展 —— 增加阻力",
    regression: "扶墙髋外展 —— 减少平衡需求",
    image_url: "",
  },
  {
    id: "high-skip",
    name: "高跳步",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "跑动中单腿起跳，对侧膝关节高抬至髋水平以上，手臂配合大幅度摆动。激活下肢爆发力，提升跑动节奏和协调性。常用于热身阶段的动态准备。",
    cue_points: [
      "起跳腿充分蹬伸（髋-膝-踝三关节伸展）",
      "对侧膝关节高抬至髋水平以上",
      "手臂大幅度摆动，对侧手-膝协调",
      "落地前脚掌缓冲，声音轻",
      "节奏稳定，每次跳步高度和距离一致",
    ],
    progression: "高跳步 + 加速跑 / 栏架高跳步",
    regression: "高抬腿走（非跳跃）—— 先建立膝驱动模式",
    image_url: "",
  },
  {
    id: "hop-with-leg-lift",
    name: "小跳后抬腿",
    body_part: "full_body",
    equipment: "bodyweight",
    description: "跑动中做小幅跳跃，每次落地后对侧腿向后上方抬起（脚跟接近臀部），激活腘绳肌和臀部。常用于热身阶段的肌肉激活。",
    cue_points: [
      "小幅跳跃，触地时间短",
      "每次落地后对侧腿快速后抬，脚跟接近臀部",
      "手臂自然摆动配合节奏",
      "核心收紧，躯干保持直立",
      "节奏稳定，动作流畅连贯",
    ],
    progression: "小跳后抬腿 + 加速跑 / 弹力带小跳后抬腿",
    regression: "原地后抬腿（非行进间）—— 先建立动作模式",
    image_url: "",
  },
];

// ====== Preset Templates (4 templates) ======

export const STRENGTH_TEMPLATES: StrengthTemplate[] = [
  {
    id: "pure-strength",
    name: "纯力量",
    description: "大重量低次数，发展最大力量和神经肌肉募集。适合准备期早期力量储备阶段。",
    difficulty: "advanced",
    exercises: [
      { exerciseId: "barbell-back-squat", sets: 5, reps: 5, load: "85% 1RM", rest: 180 },
      { exerciseId: "deadlift", sets: 5, reps: 5, load: "85% 1RM", rest: 180 },
      { exerciseId: "bench-press", sets: 5, reps: 5, load: "85% 1RM", rest: 180 },
      { exerciseId: "overhead-press", sets: 4, reps: 5, load: "85% 1RM", rest: 180 },
      { exerciseId: "bent-over-row", sets: 4, reps: 5, load: "85% 1RM", rest: 180 },
    ],
  },
  {
    id: "hypertrophy",
    name: "肌肥大",
    description: "中等重量中高次数，注重肌肉在张力下的时间。适合赛前准备期的肌肉量维持与增长。",
    difficulty: "intermediate",
    exercises: [
      { exerciseId: "barbell-back-squat", sets: 4, reps: 10, load: "70% 1RM", rest: 90 },
      { exerciseId: "bench-press", sets: 4, reps: 10, load: "70% 1RM", rest: 90 },
      { exerciseId: "romanian-deadlift", sets: 3, reps: 12, load: "65% 1RM", rest: 75 },
      { exerciseId: "cable-row", sets: 3, reps: 12, load: "65% 1RM", rest: 75 },
      { exerciseId: "dumbbell-shoulder-press", sets: 3, reps: 12, load: "65% 1RM", rest: 75 },
      { exerciseId: "dumbbell-lunges", sets: 3, reps: 10, load: "67% 1RM", rest: 75 },
      { exerciseId: "push-up", sets: 3, reps: 15, load: "自重", rest: 60 },
      { exerciseId: "pull-up", sets: 3, reps: 10, load: "自重", rest: 60 },
    ],
  },
  {
    id: "sport-power",
    name: "专项体能",
    description: "足球专项爆发力与损伤预防训练。强调动作速率、单侧稳定性和腘绳肌保护。适合赛季中维持（每周1-2次）。",
    difficulty: "intermediate",
    exercises: [
      { exerciseId: "box-jump", sets: 4, reps: 5, load: "自重", rest: 120 },
      { exerciseId: "front-squat", sets: 4, reps: 5, load: "75% 1RM（爆发性向心）", rest: 150 },
      { exerciseId: "nordic-hamstring-curl", sets: 3, reps: 5, load: "自重", rest: 120 },
      { exerciseId: "single-leg-rdl", sets: 3, reps: 8, load: "50% 1RM", rest: 90 },
      { exerciseId: "pull-up", sets: 3, reps: 6, load: "自重", rest: 90 },
      { exerciseId: "pallof-press", sets: 3, reps: 10, load: "中等", rest: 60 },
    ],
  },
  {
    id: "foundation",
    name: "基础力量",
    description: "入门级全身力量训练，建立基础动作模式。适合初学者或休赛期维持训练。",
    difficulty: "beginner",
    exercises: [
      { exerciseId: "goblet-squat", sets: 3, reps: 12, load: "50% 1RM", rest: 90 },
      { exerciseId: "push-up", sets: 3, reps: 10, load: "自重", rest: 60 },
      { exerciseId: "lat-pulldown", sets: 3, reps: 12, load: "60% 1RM", rest: 90 },
      { exerciseId: "dumbbell-shoulder-press", sets: 3, reps: 12, load: "55% 1RM", rest: 90 },
      { exerciseId: "cable-row", sets: 3, reps: 12, load: "60% 1RM", rest: 90 },
      { exerciseId: "single-leg-rdl", sets: 3, reps: 10, load: "40% 1RM", rest: 90 },
      { exerciseId: "leg-press", sets: 3, reps: 12, load: "60% 1RM", rest: 90 },
    ],
  },
];

// ====== Helpers ======

/** Look up an exercise from the library by ID */
export function findExercise(id: string): ExerciseLibItem | undefined {
  return EXERCISE_LIBRARY.find((ex) => ex.id === id);
}

/** Map body_part to module section */
export function bodyPartToSection(body_part: BodyPart): "upper" | "lower" | "core" {
  switch (body_part) {
    case "chest":
    case "shoulders":
    case "arms":
    case "upper_push":
    case "upper_pull":
      return "upper";
    case "legs":
    case "lower":
      return "lower";
    case "back":
    case "core":
    case "full_body":
      return "core";
  }
}
