import { ExerciseLibItem, StrengthTemplate, BodyPart, Equipment } from "./strength-types";

// ====== Label Maps ======

export const BODY_PART_LABELS: Record<BodyPart, string> = {
  上半身: "上半身",
  下半身: "下半身",
  全身: "全身",
};

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: "杠铃",
  dumbbell: "哑铃",
  cable: "绳索",
  bodyweight: "自重",
  machine: "器械",
  kettlebell: "壶铃",
  med_ball: "药球",
  band: "弹力带",
  bosu: "波速球",
  跳箱: "跳箱",
  other: "其他",
};

// ====== Exercise Library (22 exercises) ======

export const EXERCISE_LIBRARY: ExerciseLibItem[] = [
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["杠铃置斜方肌"],
    progression: "1.5倍深蹲（底部停顿后起至半程再下蹲）",
    regression: "自重深蹲（无负重，注重动作模式）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["杠铃置锁骨前三角肌"],
    progression: "停顿前蹲（底部停顿2秒）",
    regression: "高脚杯深蹲（壶铃置胸前，减轻腰椎压力）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["微屈膝"],
    progression: "单腿RDL",
    regression: "徒手单腿RDL（减负荷，提升单侧稳定性）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["肩胛骨靠凳"],
    progression: "单腿臀冲",
    regression: "徒手臀桥（无负重，激活臀肌感知）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "kettlebell",
    type: "力量",
    description: "",
    cue_points: ["壶铃架于胸前"],
    progression: "双壶铃前蹲",
    regression: "自重深蹲（无负重，先掌握动作模式）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "kettlebell",
    type: "力量",
    description: "",
    cue_points: ["微屈膝"],
    progression: "单腿壶铃RDL",
    regression: "徒手髋铰链练习（减负荷，感受腘绳肌拉伸）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "kettlebell",
    type: "力量",
    description: "",
    cue_points: ["壶铃托于胸前"],
    progression: "双壶铃高脚杯深蹲",
    regression: "自重深蹲（无负重，建立基础活动度）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "kettlebell",
    type: "力量",
    description: "",
    cue_points: ["双壶铃体侧悬挂"],
    progression: "过顶壶铃弓步走",
    regression: "自重弓步（无负重，稳定后再加重）",
  },
  {
    id: "",
    name: "",
    body_part: "下半身",
    equipment: "kettlebell",
    type: "力量",
    description: "",
    cue_points: ["分腿站姿"],
    progression: "后脚抬高壶铃分腿蹲",
    regression: "自重分腿蹲（无负重，降低膝髋压力）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["肩胛骨收紧"],
    progression: "暂停卧推（底部停顿2秒）",
    regression: "俯卧撑（自体重，降低肩关节压力）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["杠铃架于锁骨前"],
    progression: "借力推举",
    regression: "哑铃坐姿肩推（有靠背支撑，减少核心需求）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "barbell",
    type: "力量",
    description: "",
    cue_points: ["髋部后移"],
    progression: "潘德勒划船（每下触地）",
    regression: "弹力带划船（减负荷，更易控制）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "dumbbell",
    type: "力量",
    description: "",
    cue_points: ["哑铃置于胸侧"],
    progression: "单臂哑铃卧推",
    regression: "俯卧撑（自体重，降低肩关节压力）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "dumbbell",
    type: "力量",
    description: "",
    cue_points: ["一侧手掌和膝盖撑凳"],
    progression: "无支撑单臂哑铃划船",
    regression: "弹力带划船（减负荷，更易控制）",
  },
  {
    id: "",
    name: "",
    body_part: "上半身",
    equipment: "bodyweight",
    type: "力量",
    description: "",
    cue_points: ["正握略宽于肩"],
    progression: "负重引体向上",
    regression: "弹力带辅助引体",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "barbell",
    type: "爆发",
    description: "",
    cue_points: ["杠铃贴腿上拉"],
    progression: "悬垂高翻",
    regression: "壶铃高翻（单侧减负，降低技术要求）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "barbell",
    type: "爆发",
    description: "",
    cue_points: ["杠铃贴腿"],
    progression: "高翻（接杠）",
    regression: "哑铃耸肩（减负荷，降低协调要求）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "barbell",
    type: "爆发",
    description: "",
    cue_points: ["前架位起始"],
    progression: "半挺（不分腿）",
    regression: "哑铃火箭推（减负荷，降低肩腕压力）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "barbell",
    type: "爆发",
    description: "",
    cue_points: ["宽握距"],
    progression: "悬垂抓举",
    regression: "壶铃抓举（单侧减负，降低技术要求）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "kettlebell",
    type: "爆发",
    description: "",
    cue_points: ["壶铃后摆启动"],
    progression: "双壶铃高翻",
    regression: "轻壶铃高翻（减重量，先掌握动作节奏）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "kettlebell",
    type: "爆发",
    description: "",
    cue_points: ["髋部铰链发力"],
    progression: "单臂壶铃甩摆",
    regression: "轻壶铃甩摆（减重量，感受髋部发力）",
  },
  {
    id: "",
    name: "",
    body_part: "全身",
    equipment: "kettlebell",
    type: "爆发",
    description: "",
    cue_points: ["壶铃后摆启动"],
    progression: "双壶铃抓举",
    regression: "轻壶铃抓举（减重量，逐步建立过顶稳定）",
  },
];

// ====== Strength Templates ======

export const STRENGTH_TEMPLATES: StrengthTemplate[] = [];
